# Code style and tooling configuration for this project

[tool.black]
line-length = 100
target-version = ["py310"]
include = "\\.pyi?$"
exclude = """
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
  | app/assets
  | ui/resources\.qrc
)
/"""

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true
src_paths = ["ui", "app"]
known_first_party = ["ui", "app"]

[tool.ruff]
line-length = 100
target-version = "py310"
src = ["ui", "app"]
select = ["E", "F", "W", "I"]
# Let Black handle line-length wrapping
ignore = ["E501"]
exclude = [
  ".git",
  ".venv",
  "build",
  "dist",
  "__pycache__",
  "app/assets",
]

[tool.ruff.isort]
known-first-party = ["ui", "app"]

[tool.ruff.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]  # allow re-exports in package inits

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict_optional = true
plugins = []

